language: minimal

sudo: false

dist: trusty

git:
  submodules: false

cache:
  directories:
    - $HOME/.stack
    - $TRAVIS_BUILD_DIR/.stack-work
  timeout: 300

# We test against different Stackage snapshots.
matrix:
  include:
    - env: BUILD=stack STACK_YAML=stack.yaml
    - env: BUILD=stack STACK_YAML=stack-lts-10.0.yaml
    - env: BUILD=stack STACK_YAML=stack-lts-9.2.yaml

addons:
  apt:
    packages:
    - python
    - python-numpy
    - libgmp-dev

before_install:
 - export PATH=$HOME/.local/bin:$PATH
 - ./.travis-setup.sh

install:
 - stack build --fast alex happy
 - stack --no-terminal test --fast --only-dependencies -j 3

script:
 - stack --no-terminal test -j 1 --fast
 - stack install

 # Run integration test suite.
 - if [ "$STACK_YAML" = stack.yaml ]; then futhark-test --nobuffer tests examples; fi
 - (cd pkgtests; ./test.sh)

 # Check for style issues.
 - if [ "$STACK_YAML" = stack.yaml ]; then stack install hlint --fast && tools/style-check.sh src; fi

# EOF
